version: '3.9'

services:
  frontend_persona:
    container_name: frontend_persona
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${SERVER_PORT_HOST}:${SERVER_PORT_DOCKER}
    networks:
      - production-network

networks:
  production-network:
    driver: bridge 